# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
pod "AFNetworking", "~> 2.0"

source 'https://github.com/CocoaPods/Specs.git'

target 'my-cocoapods-test' do

end

target 'my-cocoapods-testTests' do

end

